
package it.farmadati.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.fdiwebservices.GetDataSetChangesOutput;
import org.datacontract.schemas._2004._07.fdiwebservices.GetDataSetOutput;
import org.datacontract.schemas._2004._07.fdiwebservices.GetEnabledDataSetOutput;
import org.datacontract.schemas._2004._07.fdiwebservices.GetSchemaDataSetOutput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FarmadatiItaliaWebServicesM2", targetNamespace = "http://webservices.farmadati.it")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    it.farmadati.webservices.ObjectFactory.class,
    org.datacontract.schemas._2004._07.fdiwebservices.ObjectFactory.class
})
public interface FarmadatiItaliaWebServicesM2 {


    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns org.datacontract.schemas._2004._07.fdiwebservices.GetEnabledDataSetOutput
     */
    @WebMethod(operationName = "GetEnabledDataSet", action = "http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetEnabledDataSet")
    @WebResult(name = "GetEnabledDataSetResult", targetNamespace = "http://webservices.farmadati.it")
    @RequestWrapper(localName = "GetEnabledDataSet", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetEnabledDataSet")
    @ResponseWrapper(localName = "GetEnabledDataSetResponse", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetEnabledDataSetResponse")
    public GetEnabledDataSetOutput getEnabledDataSet(
        @WebParam(name = "Username", targetNamespace = "http://webservices.farmadati.it")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://webservices.farmadati.it")
        String password);

    /**
     * 
     * @param username
     * @param codiceSetDati
     * @param tracciatoVar
     * @param password
     * @return
     *     returns org.datacontract.schemas._2004._07.fdiwebservices.GetSchemaDataSetOutput
     */
    @WebMethod(operationName = "GetSchemaDataSet", action = "http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetSchemaDataSet")
    @WebResult(name = "GetSchemaDataSetResult", targetNamespace = "http://webservices.farmadati.it")
    @RequestWrapper(localName = "GetSchemaDataSet", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetSchemaDataSet")
    @ResponseWrapper(localName = "GetSchemaDataSetResponse", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetSchemaDataSetResponse")
    public GetSchemaDataSetOutput getSchemaDataSet(
        @WebParam(name = "Username", targetNamespace = "http://webservices.farmadati.it")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://webservices.farmadati.it")
        String password,
        @WebParam(name = "CodiceSetDati", targetNamespace = "http://webservices.farmadati.it")
        String codiceSetDati,
        @WebParam(name = "TracciatoVar", targetNamespace = "http://webservices.farmadati.it")
        Boolean tracciatoVar);

    /**
     * 
     * @param modalita
     * @param username
     * @param pageN
     * @param codiceSetDati
     * @param password
     * @return
     *     returns org.datacontract.schemas._2004._07.fdiwebservices.GetDataSetOutput
     */
    @WebMethod(operationName = "GetDataSet", action = "http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetDataSet")
    @WebResult(name = "GetDataSetResult", targetNamespace = "http://webservices.farmadati.it")
    @RequestWrapper(localName = "GetDataSet", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetDataSet")
    @ResponseWrapper(localName = "GetDataSetResponse", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetDataSetResponse")
    public GetDataSetOutput getDataSet(
        @WebParam(name = "Username", targetNamespace = "http://webservices.farmadati.it")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://webservices.farmadati.it")
        String password,
        @WebParam(name = "CodiceSetDati", targetNamespace = "http://webservices.farmadati.it")
        String codiceSetDati,
        @WebParam(name = "Modalita", targetNamespace = "http://webservices.farmadati.it")
        String modalita,
        @WebParam(name = "PageN", targetNamespace = "http://webservices.farmadati.it")
        Integer pageN);

    /**
     * 
     * @param modalita
     * @param username
     * @param pageN
     * @param codiceSetDati
     * @param pagingN
     * @param password
     * @param dataIstanza
     * @return
     *     returns org.datacontract.schemas._2004._07.fdiwebservices.GetDataSetChangesOutput
     */
    @WebMethod(operationName = "GetDataSetChanges", action = "http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetDataSetChanges")
    @WebResult(name = "GetDataSetChangesResult", targetNamespace = "http://webservices.farmadati.it")
    @RequestWrapper(localName = "GetDataSetChanges", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetDataSetChanges")
    @ResponseWrapper(localName = "GetDataSetChangesResponse", targetNamespace = "http://webservices.farmadati.it", className = "it.farmadati.webservices.GetDataSetChangesResponse")
    public GetDataSetChangesOutput getDataSetChanges(
        @WebParam(name = "Username", targetNamespace = "http://webservices.farmadati.it")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://webservices.farmadati.it")
        String password,
        @WebParam(name = "CodiceSetDati", targetNamespace = "http://webservices.farmadati.it")
        String codiceSetDati,
        @WebParam(name = "DataIstanza", targetNamespace = "http://webservices.farmadati.it")
        String dataIstanza,
        @WebParam(name = "Modalita", targetNamespace = "http://webservices.farmadati.it")
        String modalita,
        @WebParam(name = "PageN", targetNamespace = "http://webservices.farmadati.it")
        Integer pageN,
        @WebParam(name = "PagingN", targetNamespace = "http://webservices.farmadati.it")
        Integer pagingN);

}
