
package it.farmadati.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FarmadatiItaliaWebServicesM2", targetNamespace = "http://webservices.farmadati.it", wsdlLocation = "http://webservices-farmadati.dyndns.ws/WS2/FarmadatiItaliaWebServicesM2.svc?singleWsdl")
public class FarmadatiItaliaWebServicesM2_Service
    extends Service
{

    private final static URL FARMADATIITALIAWEBSERVICESM2_WSDL_LOCATION;
    private final static WebServiceException FARMADATIITALIAWEBSERVICESM2_EXCEPTION;
    private final static QName FARMADATIITALIAWEBSERVICESM2_QNAME = new QName("http://webservices.farmadati.it", "FarmadatiItaliaWebServicesM2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices-farmadati.dyndns.ws/WS2/FarmadatiItaliaWebServicesM2.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FARMADATIITALIAWEBSERVICESM2_WSDL_LOCATION = url;
        FARMADATIITALIAWEBSERVICESM2_EXCEPTION = e;
    }

    public FarmadatiItaliaWebServicesM2_Service() {
        super(__getWsdlLocation(), FARMADATIITALIAWEBSERVICESM2_QNAME);
    }

    public FarmadatiItaliaWebServicesM2_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FARMADATIITALIAWEBSERVICESM2_QNAME, features);
    }

    public FarmadatiItaliaWebServicesM2_Service(URL wsdlLocation) {
        super(wsdlLocation, FARMADATIITALIAWEBSERVICESM2_QNAME);
    }

    public FarmadatiItaliaWebServicesM2_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FARMADATIITALIAWEBSERVICESM2_QNAME, features);
    }

    public FarmadatiItaliaWebServicesM2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FarmadatiItaliaWebServicesM2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FarmadatiItaliaWebServicesM2
     */
    @WebEndpoint(name = "BasicHttpBinding_FarmadatiItaliaWebServicesM2")
    public FarmadatiItaliaWebServicesM2 getBasicHttpBindingFarmadatiItaliaWebServicesM2() {
        return super.getPort(new QName("http://webservices.farmadati.it", "BasicHttpBinding_FarmadatiItaliaWebServicesM2"), FarmadatiItaliaWebServicesM2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FarmadatiItaliaWebServicesM2
     */
    @WebEndpoint(name = "BasicHttpBinding_FarmadatiItaliaWebServicesM2")
    public FarmadatiItaliaWebServicesM2 getBasicHttpBindingFarmadatiItaliaWebServicesM2(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.farmadati.it", "BasicHttpBinding_FarmadatiItaliaWebServicesM2"), FarmadatiItaliaWebServicesM2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FARMADATIITALIAWEBSERVICESM2_EXCEPTION!= null) {
            throw FARMADATIITALIAWEBSERVICESM2_EXCEPTION;
        }
        return FARMADATIITALIAWEBSERVICESM2_WSDL_LOCATION;
    }

}
